pip install ipdb
pip install pyephem
pip install pyfits
pip install configobj
pip install opencv_python-2.4.10-cp27-none-win32.whl
pip install psutil
pip install paramiko
pip install scp
pip install pyreadline
#pip install google-api-python-client
#pip install astropy